# Linear Regression

1. 보스턴 집값 데이터셋에서 YearBuilt 외에 다른 독립변수를 골라서 linear regresion 해봅시다

2. https://www.kaggle.com/datasets/budincsevity/szeged-weather
위의 데이터셋에서 독립변수를 5개 골라서 각각 linear regression을 5번 해봅시다. 온도를 가장 잘 설명하는 (=Rsquared 값이 제일 높은) feature가 누구인 지 맞혀볼까요?

3. 2의 데이터셋을 사용해서 Multiple Linear Regression을 이용해 예측을 해봅시다. train-test split을 하고, feature는 마음에 드는 걸 골라주세요. test dataset으로 성능을 보고해주세요.

In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv("train.csv")

In [3]:
from sklearn.linear_model import LinearRegression
import statsmodels.api as sm

In [4]:
y = data['SalePrice']

In [5]:
x = data.OverallCond

In [6]:
x = sm.add_constant(x)

In [7]:
model = sm.OLS(y, x).fit()

In [8]:
print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:              SalePrice   R-squared:                       0.006
Model:                            OLS   Adj. R-squared:                  0.005
Method:                 Least Squares   F-statistic:                     8.892
Date:                Wed, 15 Jul 2026   Prob (F-statistic):            0.00291
Time:                        23:10:06   Log-Likelihood:                -18540.
No. Observations:                1460   AIC:                         3.708e+04
Df Residuals:                    1458   BIC:                         3.709e+04
Df Model:                           1
Covariance Type:            nonrobust
===============================================================================
                  coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------
const        2.119e+05   1.06e+04     19.997      0.000    1.91e+05    2.33e+05
OverallCond -5558.1154   1863.962     -2.982      0.003   -9214.449   -1901.782
==============================================================================
Omnibus:                      601.288   Durbin-Watson:                   1.999
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             3406.241
Skew:                           1.843   Prob(JB):                         0.00
Kurtosis:                       9.512   Cond. No.                         29.9
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [9]:
data = pd.read_csv("weatherHistory.csv")

In [10]:
data.head()

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Daily Summary
0,2006-04-01 00:00:00.000 +0200,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,251.0,15.8263,0.0,1015.13,Partly cloudy throughout the day.
1,2006-04-01 01:00:00.000 +0200,Partly Cloudy,rain,9.355556,7.227778,0.86,14.2646,259.0,15.8263,0.0,1015.63,Partly cloudy throughout the day.
2,2006-04-01 02:00:00.000 +0200,Mostly Cloudy,rain,9.377778,9.377778,0.89,3.9284,204.0,14.9569,0.0,1015.94,Partly cloudy throughout the day.
3,2006-04-01 03:00:00.000 +0200,Partly Cloudy,rain,8.288889,5.944444,0.83,14.1036,269.0,15.8263,0.0,1016.41,Partly cloudy throughout the day.
4,2006-04-01 04:00:00.000 +0200,Mostly Cloudy,rain,8.755556,6.977778,0.83,11.0446,259.0,15.8263,0.0,1016.51,Partly cloudy throughout the day.

In [12]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 96453 entries, 0 to 96452
Data columns (total 12 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Formatted Date            96453 non-null  str
 1   Summary                   96453 non-null  str
 2   Precip Type               95936 non-null  str
 3   Temperature (C)           96453 non-null  float64
 4   Apparent Temperature (C)  96453 non-null  float64
 5   Humidity                  96453 non-null  float64
 6   Wind Speed (km/h)         96453 non-null  float64
 7   Wind Bearing (degrees)    96453 non-null  float64
 8   Visibility (km)           96453 non-null  float64
 9   Loud Cover                96453 non-null  float64
 10  Pressure (millibars)      96453 non-null  float64
 11  Daily Summary             96453 non-null  str
dtypes: float64(8), str(4)
memory usage: 8.8 MB

In [13]:
y = data['Temperature (C)']

In [16]:
x = data.Humidity

In [17]:
x = sm.add_constant(x)

In [18]:
model = sm.OLS(y, x).fit()

In [19]:
print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:        Temperature (C)   R-squared:                       0.400
Model:                            OLS   Adj. R-squared:                  0.400
Method:                 Least Squares   F-statistic:                 6.423e+04
Date:                Wed, 15 Jul 2026   Prob (F-statistic):               0.00
Time:                        23:15:58   Log-Likelihood:            -3.2991e+05
No. Observations:               96453   AIC:                         6.598e+05
Df Residuals:                   96451   BIC:                         6.598e+05
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         34.6369      0.093    373.651      0.000      34.455      34.819
Humidity     -30.8944      0.122   -253.442      0.000     -31.133     -30.655
==============================================================================
Omnibus:                     2385.781   Durbin-Watson:                   0.043
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             2566.298
Skew:                          -0.394   Prob(JB):                         0.00
Kurtosis:                       3.131   Cond. No.                         7.95
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [20]:
x = data['Wind Speed (km/h)']

In [21]:
x = sm.add_constant(x)

In [22]:
model = sm.OLS(y, x).fit()

In [23]:
print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:        Temperature (C)   R-squared:                       0.000
Model:                            OLS   Adj. R-squared:                  0.000
Method:                 Least Squares   F-statistic:                     7.739
Date:                Wed, 15 Jul 2026   Prob (F-statistic):            0.00541
Time:                        23:16:38   Log-Likelihood:            -3.5452e+05
No. Observations:               96453   AIC:                         7.090e+05
Df Residuals:                   96451   BIC:                         7.091e+05
Df Model:                           1
Covariance Type:            nonrobust
=====================================================================================
                        coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------
const                11.7989      0.057    206.699      0.000      11.687      11.911
Wind Speed (km/h)     0.0124      0.004      2.782      0.005       0.004       0.021
==============================================================================
Omnibus:                     2845.254   Durbin-Watson:                   0.026
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             1458.360
Skew:                           0.096   Prob(JB):                         0.00
Kurtosis:                       2.429   Cond. No.                         23.9
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [24]:
x = data['Wind Bearing (degrees)']

In [25]:
x = sm.add_constant(x)

In [26]:
model = sm.OLS(y, x).fit()

In [27]:
print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:        Temperature (C)   R-squared:                       0.001
Model:                            OLS   Adj. R-squared:                  0.001
Method:                 Least Squares   F-statistic:                     86.82
Date:                Wed, 15 Jul 2026   Prob (F-statistic):           1.22e-20
Time:                        23:17:21   Log-Likelihood:            -3.5448e+05
No. Observations:               96453   AIC:                         7.090e+05
Df Residuals:                   96451   BIC:                         7.090e+05
Df Model:                           1
Covariance Type:            nonrobust
==========================================================================================
                             coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------------
const                     11.4325      0.062    184.816      0.000      11.311      11.554
Wind Bearing (degrees)     0.0027      0.000      9.317      0.000       0.002       0.003
==============================================================================
Omnibus:                     2806.209   Durbin-Watson:                   0.027
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             1449.767
Skew:                           0.098   Prob(JB):                         0.00
Kurtosis:                       2.432   Cond. No.                         435.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [29]:
x = data['Visibility (km)']

In [30]:
x = sm.add_constant(x)

In [31]:
model = sm.OLS(y, x).fit()

In [32]:
print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:        Temperature (C)   R-squared:                       0.154
Model:                            OLS   Adj. R-squared:                  0.154
Method:                 Least Squares   F-statistic:                 1.760e+04
Date:                Wed, 15 Jul 2026   Prob (F-statistic):               0.00
Time:                        23:18:21   Log-Likelihood:            -3.4644e+05
No. Observations:               96453   AIC:                         6.929e+05
Df Residuals:                   96451   BIC:                         6.929e+05
Df Model:                           1
Covariance Type:            nonrobust
===================================================================================
                      coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------
const               2.6710      0.075     35.461      0.000       2.523       2.819
Visibility (km)     0.8951      0.007    132.671      0.000       0.882       0.908
==============================================================================
Omnibus:                      778.145   Durbin-Watson:                   0.075
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              698.913
Skew:                           0.165   Prob(JB):                    1.71e-152
Kurtosis:                       2.744   Cond. No.                         29.9
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [33]:
x = data['Pressure (millibars)']

In [34]:
x = sm.add_constant(x)

In [35]:
model = sm.OLS(y, x).fit()

In [36]:
print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:        Temperature (C)   R-squared:                       0.000
Model:                            OLS   Adj. R-squared:                  0.000
Method:                 Least Squares   F-statistic:                     2.862
Date:                Wed, 15 Jul 2026   Prob (F-statistic):             0.0907
Time:                        23:18:55   Log-Likelihood:            -3.5452e+05
No. Observations:               96453   AIC:                         7.091e+05
Df Residuals:                   96451   BIC:                         7.091e+05
Df Model:                           1
Covariance Type:            nonrobust
========================================================================================
                           coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------------
const                   12.3789      0.266     46.613      0.000      11.858      12.899
Pressure (millibars)    -0.0004      0.000     -1.692      0.091      -0.001    7.05e-05
==============================================================================
Omnibus:                     2786.289   Durbin-Watson:                   0.027
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             1435.356
Skew:                           0.094   Prob(JB):                         0.00
Kurtosis:                       2.433   Cond. No.                     8.72e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 8.72e+03. This might indicate that there are
strong multicollinearity or other numerical problems.

### 온도를 가장 잘 설명하는 (=Rsquared 값이 제일 높은) feature가 누구인 지 맞혀볼까요? Humidity

In [37]:
data.columns

Index(['Formatted Date', 'Summary', 'Precip Type', 'Temperature (C)',
       'Apparent Temperature (C)', 'Humidity', 'Wind Speed (km/h)',
       'Wind Bearing (degrees)', 'Visibility (km)', 'Loud Cover',
       'Pressure (millibars)', 'Daily Summary'],
      dtype='str')

In [43]:
data[['Temperature (C)','Humidity', 'Visibility (km)']]

       Temperature (C)  Humidity  Visibility (km)
0             9.472222      0.89          15.8263
1             9.355556      0.86          15.8263
2             9.377778      0.89          14.9569
3             8.288889      0.83          15.8263
4             8.755556      0.83          15.8263
...                ...       ...              ...
96448        26.016667      0.43          16.1000
96449        24.583333      0.48          15.5526
96450        22.038889      0.56          16.1000
96451        21.522222      0.60          16.1000
96452        20.438889      0.61          15.5204

[96453 rows x 3 columns]

In [44]:
df = data[['Temperature (C)', 'Humidity', 'Visibility (km)']]

In [45]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 96453 entries, 0 to 96452
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Temperature (C)  96453 non-null  float64
 1   Humidity         96453 non-null  float64
 2   Visibility (km)  96453 non-null  float64
dtypes: float64(3)
memory usage: 2.2 MB

In [46]:
df.dropna()

       Temperature (C)  Humidity  Visibility (km)
0             9.472222      0.89          15.8263
1             9.355556      0.86          15.8263
2             9.377778      0.89          14.9569
3             8.288889      0.83          15.8263
4             8.755556      0.83          15.8263
...                ...       ...              ...
96448        26.016667      0.43          16.1000
96449        24.583333      0.48          15.5526
96450        22.038889      0.56          16.1000
96451        21.522222      0.60          16.1000
96452        20.438889      0.61          15.5204

[96453 rows x 3 columns]

In [47]:
df = df.dropna()

In [48]:
y = df['Temperature (C)']

In [49]:
x= df[['Humidity', 'Visibility (km)']]

In [50]:
x = sm.add_constant(x)

In [51]:
from sklearn.model_selection import train_test_split

In [52]:
train_features, test_features, train_labels, test_labels = train_test_split(x.values, y)

In [54]:
model = LinearRegression()

In [55]:
model.fit(train_features, train_labels)

LinearRegression()

In [56]:
model.score(train_features, train_labels) # training 성능 (좋은 모델은 아닌가 보네요..)

0.4310255300017267

In [57]:
model.score(test_features, test_labels) # test 데이터에 대한 성능 (이게 논문에서 최종 보고되는 성능.)

0.42354921736200446