# 01 Titanic dataset preprocessing
1. 필요 없는 column을 지워보세요.
2. 이번엔 age는 mean으로, Embarked는 median으로 imputation해보세요.
3. Sex, Embarked column을 정수 인코딩 해보세요.

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('Titanic-Dataset.csv')

In [3]:
df.drop(['PassengerId', 'Name', 'Ticket', 'Cabin'], axis=1, inplace=True)

In [4]:
df

     Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0           0       3    male  22.0      1      0   7.2500        S
1           1       1  female  38.0      1      0  71.2833        C
2           1       3  female  26.0      0      0   7.9250        S
3           1       1  female  35.0      1      0  53.1000        S
4           0       3    male  35.0      0      0   8.0500        S
..        ...     ...     ...   ...    ...    ...      ...      ...
886         0       2    male  27.0      0      0  13.0000        S
887         1       1  female  19.0      0      0  30.0000        S
888         0       3  female   NaN      1      2  23.4500        S
889         1       1    male  26.0      0      0  30.0000        C
890         0       3    male  32.0      0      0   7.7500        Q

[891 rows x 8 columns]

In [5]:
df['Age']

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64

In [6]:
df['Age'].mean()

np.float64(29.69911764705882)

In [8]:
df['Age'].fillna(df['Age'].mean())

0      22.000000
1      38.000000
2      26.000000
3      35.000000
4      35.000000
         ...
886    27.000000
887    19.000000
888    29.699118
889    26.000000
890    32.000000
Name: Age, Length: 891, dtype: float64

In [9]:
df['Age'] = df['Age'].fillna(df['Age'].mean())

In [10]:
df

     Survived  Pclass     Sex        Age  SibSp  Parch     Fare Embarked
0           0       3    male  22.000000      1      0   7.2500        S
1           1       1  female  38.000000      1      0  71.2833        C
2           1       3  female  26.000000      0      0   7.9250        S
3           1       1  female  35.000000      1      0  53.1000        S
4           0       3    male  35.000000      0      0   8.0500        S
..        ...     ...     ...        ...    ...    ...      ...      ...
886         0       2    male  27.000000      0      0  13.0000        S
887         1       1  female  19.000000      0      0  30.0000        S
888         0       3  female  29.699118      1      2  23.4500        S
889         1       1    male  26.000000      0      0  30.0000        C
890         0       3    male  32.000000      0      0   7.7500        Q

[891 rows x 8 columns]

In [11]:
df['Embarked'].mode()

0    S
Name: Embarked, dtype: str

In [12]:
df['Embarked'].mode()[0]

'S'

In [13]:
df['Embarked'] = df['Embarked'].fillna(df['Embarked'].mode()[0])

In [14]:
df['Embarked']

0      S
1      C
2      S
3      S
4      S
      ..
886    S
887    S
888    S
889    C
890    Q
Name: Embarked, Length: 891, dtype: str

In [15]:
set(df['Embarked'])

{'C', 'Q', 'S'}

In [16]:
embarked_mapping = {'C':0, 'Q':1, 'S':2}
df['Embarked'].map(embarked_mapping)

0      2
1      0
2      2
3      2
4      2
      ..
886    2
887    2
888    2
889    0
890    1
Name: Embarked, Length: 891, dtype: int64

In [17]:
df['Embarked'] = df['Embarked'].map(embarked_mapping)

In [18]:
mapping = {'male':0, 'female':1}

In [19]:
df['Sex'].map(mapping)

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    1
889    0
890    0
Name: Sex, Length: 891, dtype: int64

In [20]:
df['Sex'] = df['Sex'].map(mapping)

In [21]:
df

     Survived  Pclass  Sex        Age  SibSp  Parch     Fare  Embarked
0           0       3    0  22.000000      1      0   7.2500         2
1           1       1    1  38.000000      1      0  71.2833         0
2           1       3    1  26.000000      0      0   7.9250         2
3           1       1    1  35.000000      1      0  53.1000         2
4           0       3    0  35.000000      0      0   8.0500         2
..        ...     ...  ...        ...    ...    ...      ...       ...
886         0       2    0  27.000000      0      0  13.0000         2
887         1       1    1  19.000000      0      0  30.0000         2
888         0       3    1  29.699118      1      2  23.4500         2
889         1       1    0  26.000000      0      0  30.0000         0
890         0       3    0  32.000000      0      0   7.7500         1

[891 rows x 8 columns]